language: r
cache: packages
latex: false
pandoc: false

env: _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - dist: xenial
    - os: osx
      brew_packages: protobuf
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - libprotoc-dev
      - libgdal-dev
      - libudunits2-dev
