language: r
cache: packages
latex: false
fortran: false

env: _R_CHECK_FORCE_SUGGESTS_=FALSE

matrix:
  include:
    - dist: precise
      r: 3.5.3
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true
    - os: osx
      brew_packages: protobuf
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler

r_packages: covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
